apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator
  namespace: autogd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: access-pods
  namespace: autogd
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operator
  namespace: autogd
subjects:
  - kind: ServiceAccount
    name: operator
    apiGroup: ""
roleRef:
  kind: Role
  name: access-pods
  apiGroup: rbac.authorization.k8s.io
