# used for development

volumes:
  postgres-data:

services:
  db:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=sgl
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 5433:8080
