apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator
  namespace: sourcegrade-lab
  labels:
    app: operator
spec:
  selector:
    matchLabels:
      app: operator
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: operator
    spec:
      serviceAccountName: operator
      containers:
        - name: operator
          image: images.sourcegrade.org/sourcegrade/lab-operator:latest
          ports:
            - containerPort: 8080
              hostPort: 80
