apiVersion: v1
kind: Service
metadata:
  name: operator
  namespace: sourcegrade-lab
spec:
  type: ClusterIP
  selector:
    app: operator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
