apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: autogd
  labels:
    app: ui
spec:
  selector:
    matchLabels:
      app: ui
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: images.sourcegrade.org/sourcegrade/quantik-ui:latest
          ports:
            - containerPort: 8080
              hostPort: 80
